---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcrepo.fullname" . }}
  labels:
{{ include "fcrepo.labels" . | indent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ include "fcrepo.postgresql.password" . | b64enc }}

  {{- if .Values.s3.enabled }}
  MODESHAPE_CONFIG: {{ "classpath:/config/jdbc-postgresql-s3/repository.json" | b64enc }}
  JAVA_OPTIONS: {{ printf "-Daws.bucket=%s -Daws.accessKeyId=%s -Daws.secretKey=%s -Dfcrepo.postgresql.host=%s -Dfcrepo.postgresql.username=%s -Dfcrepo.postgresql.password=%s -Dfcrepo.object.directory=/data/objects %s" .Values.s3.bucket .Values.s3.access_key .Values.s3.secret_key ( include "fcrepo.postgresql.host" . ) (include "fcrepo.postgresql.username" .) (include "fcrepo.postgresql.password" .) (include "fcrepo.additional_java_options" .) | b64enc }}
  {{- else }}
  MODESHAPE_CONFIG: {{ "classpath:/config/jdbc-postgresql/repository.json" | b64enc }}
  JAVA_OPTIONS: {{ printf "-Dfcrepo.postgresql.host=%s -Dfcrepo.postgresql.username=%s -Dfcrepo.postgresql.password=%s -Dfcrepo.object.directory=/data/objects -Dfcrepo.binary.directory=/data/binaries %s" ( include "fcrepo.postgresql.host" . ) (include "fcrepo.postgresql.username" .) (include "fcrepo.postgresql.password" .) (include "fcrepo.additional_java_options" .) | b64enc }}
  {{- end }}
